# Generated by Django 2.2.2 on 2019-12-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title_or_position', models.CharField(max_length=255, verbose_name='Title or Position')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('image', models.ImageField(upload_to='cutomer_images')),
                ('feedback_message', models.TextField()),
                ('feedback_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ('feedback_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('upload_date', '-title'), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
    ]
