# Generated by Django 2.2.2 on 2019-12-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191209_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-feedback_date',), 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-upload_date',), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='cutomer_images', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title_or_position',
            field=models.CharField(max_length=255, verbose_name='Designation'),
        ),
    ]
